#DataSource Configuration
spring:
  datasource:
    driver-class-name:  oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orclcdb
    username: system
    password: oracle

# JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql : true

server:
  port: 9191

logging:
  file: D:/log/product-service/elkdata-stack.log


# EMAIL config

